# MGCDB configuration file. Copy to a desired location and edit.
# See instructions in README.md for more information.

# Location where the database file should be
db_location = "~/mgcdb.sqlite"

# Steam API key
# Get this at https://steamcommunity.com/dev/apikey
steam_key = ""

# Base URL of this site. Should end with a slash.
# Used for redirecting the user after logging in with OpenID
url = "http://example.com/"
